export let keyboardRowsData = [
  {
    keys: [
      { data: 192, value: "~" },
      { data: 49, value: "1" },
      { data: 50, value: "2" },
      { data: 51, value: "3" },
      { data: 52, value: "4" },
      { data: 53, value: "5" },
      { data: 54, value: "6" },
      { data: 55, value: "7" },
      { data: 56, value: "8" },
      { data: 57, value: "9" },
      { data: 48, value: "0" },
      { data: 189, value: "-" },
      { data: 187, value: "+" },
    ],
  },
  {
    keys: [
      { data: 8, value: "Backspace", class: "delete" },
      { data: 9, value: "Tab", class: "tab" },
      { data: 81, value: "Q" },
      { data: 87, value: "W" },
      { data: 69, value: "E" },
      { data: 82, value: "R" },
      { data: 84, value: "T" },
      { data: 89, value: "Y" },
      { data: 85, value: "U" },
      { data: 73, value: "I" },
      { data: 79, value: "O" },
      { data: 80, value: "P" },
      { data: 219, value: "[" },
      { data: 221, value: "]" },
      { data: 220, value: "\\" },
    ],
  },
  {
    keys: [
      { data: 20, value: "CapsLock", class: "capslock" },
      { data: 65, value: "A" },
      { data: 83, value: "S" },
      { data: 68, value: "D" },
      { data: 70, value: "F" },
      { data: 71, value: "G" },
      { data: 72, value: "H" },
      { data: 74, value: "J" },
      { data: 75, value: "K" },
      { data: 76, value: "L" },
      { data: 186, value: ";" },
      { data: 222, value: "'" },
      { data: 13, value: "Enter", class: "return" },
    ],
  },
  {
    keys: [
      { data: 16, value: "Shift", class: "leftshift" },
      { data: 90, value: "Z" },
      { data: 88, value: "X" },
      { data: 67, value: "C" },
      { data: 86, value: "V" },
      { data: 66, value: "B" },
      { data: 78, value: "N" },
      { data: 77, value: "M" },
      { data: 188, value: "," },
      { data: 190, value: "." },
      { data: 191, value: "/" },
      { data: 16, value: "Shift", class: "rightshift" },
    ],
  },
  {
    keys: [
      { data: 17, value: "Ctrl", class: "leftctrl" },
      { data: 18, value: "Alt" },
      { data: 90, value: "Command" },
      { data: 32, value: "Space", class: "space" },
      { data: 90, value: "Command" },
      { data: 18, value: "Alt" },
      { data: 17, value: "Ctrl" },
      { data: 0, value: "Fn" },
    ],
  },
];
